### ISSUE TITLE
Should transforms operate on "completion value"?

### ISSUE THREAD

**Issue by RangerMauve** [leebyron/ecmascript-iterator-hof#3]
The new [for ... of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of) syntax ignores the completion value, so it would make sense to ignore it for the different functions introduced here.

```javascript
function *example(){
 yield 1;
 yield 2;
 return 3;
}

for(let i of example()) console.log(i);
```

Outputs

```
1
2
```

**Comment by leebyron** [comment]
Yeah that's very likely correct, completion values should be ignored.
