### ISSUE TITLE
Spec functions as generators

### ISSUE THREAD

**Issue by edevine** [leebyron/ecmascript-iterator-hof#6]
Is this an opportunity to spec the functions as generators? A few examples:
```
class Iterator {
    *concat(...iterators) {
        yield* this;
        for (iterator in iterators) {
            yield* iterator;
        }
    }

    *map(mapFn) {
        for (value in this) {
            yield mapFn(value);
        }
    }

    *filter(filterFn) {
        for (value in this) {
            if (filterFn(value)) {
                yield value;
            }
        }
    }

    *flatten() {
        for (iterator in this) {
            yield* iterator;
        }
    }
}
```

**Comment by leebyron** [comment]
No other operations defined in the ECMAScript specification are written in terms of generators. I'm happy to use the behavior of the generator form to inform how the behavior should work, but I'm attempting to be careful to write the proposal in a way that is amenable to addition to the specification.
