### ISSUE TITLE
Are there any plans to submit this proposal to TC39?

### ISSUE THREAD

**Issue by zloirock** [leebyron/ecmascript-iterator-hof#9]
There were several discussions about something like that from pre-es6 strawmans, but it's still missed in https://github.com/tc39/proposals

**Comment by zloirock** [comment]
cc @leebyron it the actual question, because I don't know, should the experimental implementation of this proposal be added to `core-js` -> `babel-polyfill` or not.

**Comment by ljharb** [comment]
Prior to presentation to tc39, the answer is always “not” - at this point, I’d look to https://github.com/tc39/proposal-iterator-helpers/
